# Generated by Django 6.0 on 2026-05-18 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Classes', '0006_remove_staffassignments_status'),
        ('UserDetails', '0008_userdetails_class_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('COMPLETED', 'COMPLETED'), ('DROPPED', 'DROPPED')], default='ACTIVE', max_length=20)),
                ('enrolled_date', models.DateTimeField(auto_now_add=True)),
                ('assigned_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_enrollments', to='Classes.staffassignments')),
                ('enrolled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrolled_students', to='UserDetails.userdetails')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollments', to='UserDetails.userdetails')),
            ],
            options={
                'db_table': 'student_enrollments',
            },
        ),
    ]
