# Generated by Django 6.0 on 2026-05-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='assigned_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classes',
            name='available_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
