# Generated by Django 6.0 on 2026-05-09 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classes', '0002_classes_assigned_date_classes_available_date'),
        ('UserDetails', '0008_userdetails_class_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffAssignments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
                ('class_time', models.CharField(max_length=100)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('available_date', models.DateField(blank=True, null=True)),
                ('assigned_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserDetails.userdetails')),
            ],
            options={
                'db_table': 'staff_assignments',
            },
        ),
    ]
