# Generated by Django 6.0 on 2026-05-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classes', '0003_staffassignments'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffassignments',
            name='class_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffassignments',
            name='class_status',
            field=models.CharField(default='OPEN', max_length=20),
        ),
        migrations.AddField(
            model_name='staffassignments',
            name='student_limit',
            field=models.IntegerField(default=50),
        ),
    ]
