# Generated by Django 6.0 on 2026-05-13 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Classes', '0004_staffassignments_class_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffassignments',
            name='available_date',
        ),
    ]
