# Generated by Django 6.0 on 2026-05-13 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Classes', '0005_remove_staffassignments_available_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffassignments',
            name='status',
        ),
    ]
