# Generated by Django 6.0 on 2026-05-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classes', '0006_remove_staffassignments_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffassignments',
            name='available_slot',
            field=models.IntegerField(default=0),
        ),
    ]
