# Generated by Django 6.0 on 2026-05-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classes', '0007_staffassignments_available_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffassignments',
            name='class_end_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
