# Generated by Django 6.0 on 2026-05-30 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classes', '0008_staffassignments_class_end_date'),
        ('Enrollments', '0001_initial'),
        ('UserDetails', '0009_userdetails_purchased_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField()),
                ('attendance_status', models.CharField(choices=[('PRESENT', 'PRESENT'), ('ABSENT', 'ABSENT')], default='PRESENT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Classes.staffassignments')),
                ('marked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserDetails.userdetails')),
                ('student_enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Enrollments.studentenrollment')),
            ],
            options={
                'db_table': 'student_attendance',
                'unique_together': {('student_enrollment', 'assigned_class', 'attendance_date')},
            },
        ),
    ]
