# Generated by Django 6.0 on 2026-06-04 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserDetails', '0009_userdetails_purchased_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffLeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('SICK', 'SICK'), ('CASUAL', 'CASUAL'), ('PERSONAL', 'PERSONAL'), ('EMERGENCY', 'EMERGENCY'), ('OTHER', 'OTHER')], max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], default='PENDING', max_length=20)),
                ('admin_remarks', models.TextField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_leave_requests', to='UserDetails.userdetails')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserDetails.userdetails')),
            ],
        ),
    ]
