# Generated by Django 6.0 on 2026-06-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeaveRequest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffleaverequest',
            name='reason',
        ),
        migrations.AddField(
            model_name='staffleaverequest',
            name='total_days',
            field=models.IntegerField(default=1),
        ),
    ]
