# Generated by Django 6.0.6 on 2026-07-02 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeaveRequest', '0002_remove_staffleaverequest_reason_and_more'),
        ('UserDetails', '0009_userdetails_purchased_course_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffleaverequest',
            options={'verbose_name': 'Staff Leave Request', 'verbose_name_plural': 'Staff Leave Requests'},
        ),
        migrations.AlterModelTable(
            name='staffleaverequest',
            table='staff_leave_request',
        ),
        migrations.CreateModel(
            name='StudentLeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('SICK', 'SICK'), ('CASUAL', 'CASUAL'), ('PERSONAL', 'PERSONAL'), ('EMERGENCY', 'EMERGENCY'), ('OTHER', 'OTHER')], max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_days', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], default='PENDING', max_length=20)),
                ('staff_remarks', models.TextField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_student_leave_requests', to='UserDetails.userdetails')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserDetails.userdetails')),
            ],
            options={
                'verbose_name': 'Student Leave Request',
                'verbose_name_plural': 'Student Leave Requests',
                'db_table': 'student_leave_request',
            },
        ),
    ]
