# Generated by Django 5.2.4 on 2026-02-05 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserDetails', '0003_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
