# Generated by Django 6.0 on 2026-05-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDetails', '0005_alter_userdetails_id_alter_userdetails_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='class_name',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
