# Generated by Django 6.0 on 2026-05-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDetails', '0006_userdetails_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='assigned_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='availability',
            field=models.CharField(default='AVAILABLE', max_length=20),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='available_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
