# Generated by Django 6.0 on 2026-05-09 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDetails', '0007_userdetails_assigned_date_userdetails_availability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='class_time',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
