# Generated by Django 6.0 on 2026-05-18 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0002_rename_course_courses'),
        ('UserDetails', '0008_userdetails_class_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='purchased_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Courses.courses'),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='student_unique_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
