# Generated by Django 6.0 on 2026-05-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0002_rename_course_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='related_classes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
