# Generated by Django 6.0 on 2026-05-12 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='extra_data',
            field=models.JSONField(default=dict),
        ),
    ]
