# Generated by Django 6.0 on 2026-06-11 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0002_notifications_extra_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
